### ISSUE TITLE
NULL pointer deference with Navigo Liberté+

### ISSUE THREAD

**Issue by fmatray** [luu176/Metroflip#31]
Metroflip reboot when reading a Navigo Liberté+ (paris métro) with a message "FLIPPER CRASHED AND WAS REBOOTED.    NULL pointer deference".
I can read the card, see first pages (Contract, environment, Event1) but when I click on right (Next), it crashes everytime. 

I'm using Momentum 009 with the included metroflip version.

**Comment by fmatray** [comment]
I ran another test and perhaps it's because there is only one event on the card, but I'm not sure.

**Comment by DocSystem** [comment]
Should now be fixed on branch `dev`: https://github.com/luu176/Metroflip/tree/dev

**Comment by fmatray** [comment]
I tried the 0.5 beta. And I still have the bug with one Navigo but not the other.

**Comment by DocSystem** [comment]
Can you try building the dev branch yourself? The last release doesn't include the fix yet!

**Comment by DocSystem** [comment]
It's probably because there's an unknown station in the last events! Did you go to Grand Paris metro stations (new metro line 14 stations) recently?

**Comment by fmatray** [comment]
I compiled the dev version and it works.

We live next to the new extension of the ligne 14.
